{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2023-37453",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://syzkaller.appspot.com/bug?extid=18996170f8096c6174d0",
        "name": "https://syzkaller.appspot.com/bug?extid=18996170f8096c6174d0",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lore.kernel.org/all/000000000000c0ffe505fe86c9ca%40google.com/T/",
        "name": "https://lore.kernel.org/all/000000000000c0ffe505fe86c9ca%40google.com/T/",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://lore.kernel.org/all/000000000000e56434059580f86e%40google.com/T/",
        "name": "https://lore.kernel.org/all/000000000000e56434059580f86e%40google.com/T/",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=1e4c574225cc5a0553115e5eb5787d1474db5b0f",
        "name": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=1e4c574225cc5a0553115e5eb5787d1474db5b0f",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=85d07c55621676d47d873d2749b88f783cd4d5a1",
        "name": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=85d07c55621676d47d873d2749b88f783cd4d5a1",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=de28e469da75359a2bb8cd8778b78aa64b1be1f4",
        "name": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=de28e469da75359a2bb8cd8778b78aa64b1be1f4",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ff33299ec8bb80cdcc073ad9c506bd79bb2ed20b",
        "name": "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ff33299ec8bb80cdcc073ad9c506bd79bb2ed20b",
        "refsource": "",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "An issue was discovered in the USB subsystem in the Linux kernel through 6.4.2. There is an out-of-bounds and crash in read_descriptors in drivers/usb/core/sysfs.c."
      }
    ]
  }
}