{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2023-43785",
    "ASSIGNER": "secalert@redhat.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2242252",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2242252",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://access.redhat.com/security/cve/CVE-2023-43785",
        "name": "https://access.redhat.com/security/cve/CVE-2023-43785",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20231103-0006/",
        "name": "https://security.netapp.com/advisory/ntap-20231103-0006/",
        "refsource": "MISC",
        "tags": []
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2024:2145",
        "name": "RHSA-2024:2145",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2024:2973",
        "name": "RHSA-2024:2973",
        "refsource": "",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "A vulnerability was found in libX11 due to a boundary condition within the _XkbReadKeySyms() function. This flaw allows a local user to trigger an out-of-bounds read error and read the contents of memory on the system."
      }
    ]
  }
}