{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2019-11934",
    "ASSIGNER": "cve-assign@fb.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://www.facebook.com/security/advisories/cve-2019-11934",
        "name": "https://www.facebook.com/security/advisories/cve-2019-11934",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/facebook/folly/commit/c321eb588909646c15aefde035fd3133ba32cdee",
        "name": "https://github.com/facebook/folly/commit/c321eb588909646c15aefde035fd3133ba32cdee",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "Improper handling of close_notify alerts can result in an out-of-bounds read in AsyncSSLSocket. This issue affects folly prior to v2019.11.04.00."
      }
    ]
  }
}