{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2019-17040",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://github.com/rsyslog/rsyslog/pull/3875",
        "name": "https://github.com/rsyslog/rsyslog/pull/3875",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/rsyslog/rsyslog/blob/v8-stable/ChangeLog",
        "name": "https://github.com/rsyslog/rsyslog/blob/v8-stable/ChangeLog",
        "refsource": "CONFIRM",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/W6SUQE25RD37CD24BHKUWMG27U5RQ2FU/",
        "name": "FEDORA-2019-ea7d5876a4",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KPNCHI7X2IEXRH6RYD6IDPR4PLB5RPC7/",
        "name": "FEDORA-2019-1fb95ae48d",
        "refsource": "",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "contrib/pmdb2diag/pmdb2diag.c in Rsyslog v8.1908.0 allows out-of-bounds access because the level length is mishandled."
      }
    ]
  }
}