{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2022-42040",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-434"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://pypi.org/project/democritus-dicts/",
        "name": "https://pypi.org/project/democritus-dicts/",
        "refsource": "MISC",
        "tags": [
          "Product",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/dadadadada111/info/issues/1",
        "name": "https://github.com/dadadadada111/info/issues/1",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/d8s-algorithms/",
        "name": "https://pypi.org/project/d8s-algorithms/",
        "refsource": "MISC",
        "tags": [
          "Product",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "The d8s-algorithms package for Python, as distributed on PyPI, included a potential code-execution backdoor inserted by a third party. The backdoor is the democritus-dicts package. The affected version is 0.1.0."
      }
    ]
  }
}